'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class Archives

        '''<summary>
        '''Header1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Header1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''phCurrentArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCurrentArticles As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblCurrentArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentArticles As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phArchives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phArchives As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblLatest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLatest As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCategory As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblByCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblByCategory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''phAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phAuthor As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblByAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblByAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptAuthors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptAuthors As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''phMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMonth As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblByMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblByMonth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptMonth As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Header2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Header2 As Global.Ventrian.NewsArticles.ucHeader
    End Class
End Namespace
