'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class LatestCommentsOptions

        '''<summary>
        '''tblLatestCommentsDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLatestCommentsDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCommentCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommentCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCommentCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommentCount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valCountType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCountType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplate As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeStylesheet As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlBody As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlNoComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlNoComments As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlNoComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlNoComments As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
