'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class LatestArticlesOptions

        '''<summary>
        '''tblLatestArticlesDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLatestArticlesDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plLaunchLinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLaunchLinks As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkLaunchLinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLaunchLinks As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plBubbleFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBubbleFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkBubbleFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBubbleFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plArticleCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plArticleCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtArticleCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtArticleCount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valCountType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCountType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''dshFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFilterSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFilterSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plArticleIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plArticleIDs As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtArticleIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtArticleIDs As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAllCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllCategories As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rdoMatchOperator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoMatchOperator As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''lstCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCategories As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblHoldCtrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHoldCtrl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCategoriesExclude control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoriesExclude As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstCategoriesExclude control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCategoriesExclude As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblHoldCtrl2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHoldCtrl2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plStartPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartPoint As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtStartPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartPoint As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblStartPoint2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartPoint2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valStartPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStartPoint As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valStartPointIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStartPointIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStartDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStartDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxAge As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxAge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxAge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valMaxAgeType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxAgeType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnablePager As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnablePager As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPageSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPageSizeIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPageSizeIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plShowPending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowPending As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowPending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowPending As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowRelated As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowRelated As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFeaturedOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFeaturedOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plNotFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotFeaturedOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkNotFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotFeaturedOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSecureOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSecureOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSecureOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSecureOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plNotSecureOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotSecureOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkNotSecureOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotSecureOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomField As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCustomField As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCustomFieldValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomFieldValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLinkFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLinkFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoLinkFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoLinkFilter As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtUrlFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrlFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpPageFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPageFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ctlLinkFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLinkFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''dshAuthorFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAuthorFilterSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAuthorFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAuthorFilterSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthor As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblAuthorFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSelectAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectAuthor As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ddlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAuthor As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plQueryStringFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plQueryStringFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkQueryStringFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkQueryStringFilter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plQueryStringParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plQueryStringParam As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtQueryStringParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQueryStringParam As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plUsernameFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUsernameFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUsernameFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUsernameFilter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plUsernameParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUsernameParam As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtUsernameParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUsernameParam As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLoggedInUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoggedInUser As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkLoggedInUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLoggedInUser As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshTagFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTagFilterSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTagFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTagFilterSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''rdoTagsMatchOperator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoTagsMatchOperator As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTags As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTags As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplate As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeStylesheet As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstLayoutMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlBody As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trItemsPerRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemsPerRow As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valItemsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plHtmlNoArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlNoArticles As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlNoArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlNoArticles As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshTemplateSaves control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplateSaves As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplateSaves control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplateSaves As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''trLoadFromTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLoadFromTemplate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plLoadFromTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoadFromTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpLoadFromTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpLoadFromTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdLoadTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plSaveTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSaveTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSaveTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSaveTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSaveTemplateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSaveTemplateText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSaveTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dshTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplateHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplateHelp As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblTemplateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTemplateHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHeaderFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderFooter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblAuthorToken control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorToken As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRssLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRssLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSort As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSortXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTimeXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItem As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblArticleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblArticleLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorUserName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorFullName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCommentLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommentLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreateDateXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateDateXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCommentCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCommentCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEdit As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasCommentsEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasCommentsEnabled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasMoreDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasMoreDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasMultiplePages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasMultiplePages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHasRatingsEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHasRatingsEnabled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImageLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImageThumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageThumb As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImageThumbLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImageThumbLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLinkTarget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkTarget As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModuleID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPageCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPageText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublishStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublishStartDateXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishStartDateXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublishStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishStartTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublishEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublishEndTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublishEndTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRating As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRatingCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRatingCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRatingDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRatingDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSummary As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSummaryXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSummaryXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUpdateDateXXX control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdateDateXXX As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUpdateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdateTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblViewCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewCount As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
