'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class NewsArchivesOptions

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''drpMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divHideZeroCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divHideZeroCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''chkHideZeroCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideZeroCategories As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divParentCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divParentCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''drpParentCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpParentCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divMaxDepth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divMaxDepth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtMaxDepth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxDepth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxDepth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxDepth As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''divAuthorSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAuthorSortBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''drpAuthorSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAuthorSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divGroupBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divGroupBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''drpGroupBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpGroupBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rdoLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoLayoutMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''divItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divItemsPerRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valItemsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlFooter As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
