'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class NewsArchives

        '''<summary>
        '''rptNewsArchives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptNewsArchives As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''dlNewsArchives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlNewsArchives As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''divNotConfigured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNotConfigured As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
