'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucAdminOptions

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''lblMainOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMainOptions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMainOptionsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMainOptionsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategoriesDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategoriesDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomFields As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomFieldsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomFieldsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImportFeeds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImportFeeds As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImportFeedsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImportFeedsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTags As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTagsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTagsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailTemplates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailTemplatesDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailTemplatesDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trSiteTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSiteTemplates As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblSiteTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSiteTemplates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSiteTemplatesDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSiteTemplatesDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ucHeader2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader2 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''cmdImport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdImport As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
