'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucEditCustomFields

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''grdCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCustomFields As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblNoCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoCustomFields As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdAddCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddCustomField As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
