'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucEditCustomField

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''dshCustomFieldDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCustomFieldDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCustomFieldDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCustomFieldDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCustomFieldDetailsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomFieldDetailsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaption As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCaption As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCaptionHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptionHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCaptionHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaptionHelp As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plFieldType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpFieldType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpFieldType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFieldElements As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldElements As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstFieldElementType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstFieldElementType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFieldElements As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldElements As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valFieldElements As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblFieldElementHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFieldElementHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDefaultValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultValue As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDefaultValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefaultValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plVisible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plVisible As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkVisible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkVisible As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trMaximumLength As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaximumLength As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximumLength As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaximumLengthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaximumLengthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''phRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRequired As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshRequiredDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRequiredDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequiredDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRequired As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequired As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plValidationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plValidationType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpValidationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpValidationType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRegex As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegex As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
