'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucImportFeed

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''pnlSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSettings As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshFeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFeed As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblFeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFeed As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblFeedSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFeedSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUrl As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valUrl As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIsActive As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshArticleSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshArticleSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblArticle As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plArticleSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plArticleSettings As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAutoFeature control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoFeature As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAutoFeature control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoFeature As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAutoExpire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoExpire As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAutoExpire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAutoExpire As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpAutoExpire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAutoExpire As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDateMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDateMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstDateMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstDateMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthor As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSelectAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectAuthor As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAuthor As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAuthorUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAuthor As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCategories As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
