'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucImportFeeds

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''grdFeeds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdFeeds As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblNoFeeds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoFeeds As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdAddFeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddFeed As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''phScheduler control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phScheduler As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshSchedulerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSchedulerSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSchedulerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSchedulerSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSchedulerSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchedulerSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSchedulerEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSchedulerEnabled As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTimeLapse As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeLapse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpTimeLapseMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTimeLapseMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRetryTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRetryTimeLapse As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRetryTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRetryTimeLapse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpRetryTimeLapseMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRetryTimeLapseMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDeleteArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDeleteArticles As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDeleteArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDeleteArticles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dshSchedulerHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSchedulerHistory As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSchedulerHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSchedulerHistory As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSchedulerHistoryHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchedulerHistoryHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNoHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgScheduleHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgScheduleHistory As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblScheduler control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblScheduler As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
