'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucMyArticles

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''chkShowAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowAll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''grdMyArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdMyArticles As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''ctlPagingControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlPagingControl As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''phNoArticles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phNoArticles As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''Header1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Header1 As Global.Ventrian.NewsArticles.ucHeader
    End Class
End Namespace
