'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles

    Partial Public Class ucSubmitNews

        '''<summary>
        '''ucHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader1 As Global.Ventrian.NewsArticles.ucHeader

        '''<summary>
        '''phMirrorText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMirrorText As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblMirrorText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMirrorText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phMirror control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMirror As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshMirror control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshMirror As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblMirror control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblMirror As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblMirrorHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMirrorHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plMirrorArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMirrorArticle As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkMirrorArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMirrorArticle As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trMirrorModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trMirrorModule As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMirrorModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMirrorModule As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpMirrorModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpMirrorModule As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trMirrorArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trMirrorArticle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMirrorArticleSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMirrorArticleSelect As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpMirrorArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpMirrorArticle As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valMirrorArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMirrorArticle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trMirrorAutoUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trMirrorAutoUpdate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMirrorAutoUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMirrorAutoUpdate As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkMirrorAutoUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMirrorAutoUpdate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''phCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCreate As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCreate As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCreate As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCreateHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgSpacer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSpacer1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBody As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''valBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valBody As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''phAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phAttachment As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAttachment As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAttachment As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''trLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLink As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLink As Global.System.Web.UI.UserControl

        '''<summary>
        '''ctlUrlLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlUrlLink As Global.System.Web.UI.UserControl

        '''<summary>
        '''trNewWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trNewWindow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plNewWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNewWindow As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkNewWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNewWindow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ucUploadFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucUploadFiles As Global.Ventrian.NewsArticles.Controls.UploadFiles

        '''<summary>
        '''ucUploadImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucUploadImages As Global.Ventrian.NewsArticles.Controls.UploadImages

        '''<summary>
        '''phExcerpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phExcerpt As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshExcerpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshExcerpt As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblExcerpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblExcerpt As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''txtExcerptBasic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExcerptBasic As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtExcerptRich control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExcerptRich As Global.System.Web.UI.UserControl

        '''<summary>
        '''phMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMeta As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshMeta As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblMeta As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plMetaTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMetaTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMetaTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMetaTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plMetaDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMetaDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMetaDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMetaDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plMetaKeyWords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMetaKeyWords As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMetaKeyWords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMetaKeyWords As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPageHeadText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageHeadText As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageHeadText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageHeadText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''phCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCustomFields As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCustomFields As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCustomFields As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''rptCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCustomFields As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''phOrganize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phOrganize As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshOrganize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshOrganize As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblOrganize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblOrganize As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plOrganizeHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOrganizeHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgSpacer2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSpacer2 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''trCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCategories As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCategories As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''valCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''trTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTags As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdTxtTagsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTxtTagsTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''tdTxtTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTxtTags As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''txtTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTags As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTags As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tdAllTagsTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAllTagsTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plAllTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''tdAllTagsList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAllTagsList As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lstTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTags As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''addTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addTags As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''replaceTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents replaceTags As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''tdStaticTagsList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdStaticTagsList As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plArticleTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plArticleTags As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstFinalTags control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstFinalTags As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''cmdUp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUp As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDown As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDeleteTag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteTag As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''phPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPublish As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPublish As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPublish As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plPublishHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPublishHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgSpacer3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSpacer3 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''trAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAuthor As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthor As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSelectAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectAuthor As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ddlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAuthor As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAuthor As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAuthorUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAuthor As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''trFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFeatured As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trSecure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSecure As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSecure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSecure As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSecure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSecure As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPublish As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublishDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdPublishCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPublishCalendar As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valPublishDateRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPublishDateRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPublishDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtPublishHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublishHour As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPublishMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublishMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trExpiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trExpiry As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEndDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpiryDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdExpiryCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdExpiryCalendar As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valExpiryDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtExpiryHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpiryHour As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtExpiryMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpiryMinute As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAction As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAction As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgSpacer4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSpacer4 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdSaveArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveArticle As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPublishArticle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPublishArticle As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdAddEditPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddEditPages As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''valMessageBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMessageBox As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ucHeader2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucHeader2 As Global.Ventrian.NewsArticles.ucHeader
    End Class
End Namespace
