'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles.Controls
    
    Partial Public Class Honeypot
        
        '''<summary>
        '''ConfirmEmailLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmEmailLabel As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtConfirmEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtConfirmEmail As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''RecaptchaValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RecaptchaValidator As Global.System.Web.UI.WebControls.CustomValidator
    End Class
End Namespace
