'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles.Controls

    Partial Public Class UploadImages

        '''<summary>
        '''litModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litModuleID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTabModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTabModuleID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTicketID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTicketID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litArticleGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litArticleGuid As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblSelectImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectImages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblImages As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblImagesHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImagesHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phImages As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''trUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''dshUploadImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshUploadImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblUploadImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUploadImages As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFolder As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpUploadImageFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpUploadImageFolder As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trExisting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trExisting As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''dshExistingImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshExistingImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblExistingImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblExistingImages As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ctlImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlImage As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdAddExistingImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddExistingImage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dshSelectedImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSelectedImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSelectedImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSelectedImages As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''dlImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlImages As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''lblNoImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoImages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phExternalImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phExternalImage As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshExternalImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshExternalImage As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblExternalImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblExternalImage As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plImageUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageUrl As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImageExternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImageExternal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdRefreshPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRefreshPhotos As Global.Ventrian.NewsArticles.Components.WebControls.RefreshControl
    End Class
End Namespace
