'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.NewsArticles.Controls
    
    Partial Public Class UploadFiles
        
        '''<summary>
        '''litModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litModuleID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTabModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTabModuleID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTicketID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTicketID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litArticleGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litArticleGuid As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''dshFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFiles As DotNetNuke.UI.UserControls.SectionHeadControl
        
        '''<summary>
        '''tblFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFiles As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''lblFilesHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilesHelp As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''trUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''dshUploadFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshUploadFiles As DotNetNuke.UI.UserControls.SectionHeadControl
        
        '''<summary>
        '''tblUploadFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUploadFiles As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''plFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFolder As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''drpUploadFilesFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpUploadFilesFolder As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''fupFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fupFile As Global.System.Web.UI.WebControls.FileUpload
        
        '''<summary>
        '''btUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btUpload As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''trExisting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trExisting As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''dshExistingFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshExistingFiles As DotNetNuke.UI.UserControls.SectionHeadControl
        
        '''<summary>
        '''tblExistingFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblExistingFiles As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''ctlFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFile As DotNetNuke.UI.UserControls.UrlControl
        
        '''<summary>
        '''cmdAddExistingFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddExistingFile As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''dshSelectedFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSelectedFiles As DotNetNuke.UI.UserControls.SectionHeadControl
        
        '''<summary>
        '''tblSelectedFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSelectedFiles As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''dlFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlFiles As Global.System.Web.UI.WebControls.DataList
        
        '''<summary>
        '''lblNoFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoFiles As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cmdRefreshFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRefreshFiles As Global.Ventrian.NewsArticles.Components.WebControls.RefreshControl
    End Class
End Namespace
